### ISSUE TITLE
[PDF Merge Conflicts] vs [Latest PDF Availability]

### ISSUE THREAD

**Issue by jensenr30** [milesdai/TAoE3Solutions#17]
It would be nice if we could find a way to both:
(a) have the latest PDF automatically available to people who view this repository
(b) not have these pointless merge conflicts with different renderings of the PDF.

**Comment by milesdai** [comment]
Yeah that's a good point. I thought about this for a bit, and I think the best way to solve this would probably be to set up a Github workflow to build the document for each commit and publish the PDF as an artifact. I can look into setting up something like that, but this will take some time.

**Comment by jensenr30** [comment]
@milesdai  
@K4LCIFER has just started building https://github.com/OpenTextbookSolutions/open-textbook-solutions 
He has talked about setting up a website for open source textbook solutions, and possibly eventually having solutions compiled from LaTeX to PDF on his website.
I'm not sure which way to go about this is best.  @K4LCIFER has talked about formatting the LaTeX source in such a way to make the answers searchable.  Maybe we could adopt a standard way to make the exercises searchable, or maybe he could adopt a standard from the existing document we have.  Or if no solution can be found that satisfied both parties, @K4LCIFER could just maintain a copy of this repo with his own modifications to source, but that would be less elegant, producing two different version of the same document...  Food for thought.

**Comment by milesdai** [comment]
I see -- thanks for pointing me to the repo. It looks like an interesting idea to me, and I'd be curious to see where it goes, but at the moment, this is still very much a side project for me. To that end, I would like to keep the scope more limited. If the opentextbooksolutions.org site takes off, then I'd be happy to see if we can find a working standardized format. Will definitely keep this in mind though!

With regards to making Latex searchable, this is not such a high priority for me in that it seems to go against the purpose of Latex as a markup language (unless you're talking about modifications that will make the PDF more searchable).

**Comment by K4LCIFER** [comment]
Just for clarification with regarding the formatting: what I was mostly referring to was keeping the questions separated; what I mean by this is that I am thinking of formatting my submissions in such a way so that questions are easily delimited by their respective sections. This would allow me to just pull a specific set of pages that contain the question that is requested and throw them onto the webpage; whereas, if the questions were mixed on pages, then its possible that if someone requests a question they may have two separate questions popping up on the same page.

**Comment by milesdai** [comment]
Add a basic latex compilation CI workflow in 3be8aa413a0e4ca6465aa4939bbc4180a5e08f49.
This allows the built PDF artifact to be downloaded from the "Actions" tab.

This solutions still leaves some features to be desired:
1. Downloading the file now gives you a zip file. There is currently no good way to avoid this. This is really annoying if I want to view the pdf associated with a specific PR for example or if someone else wants to just preview the project quickly.
2. The retention period on the pdf is only 90 days. If this project sees no progress in that time, then the file will be deleted. But also, if many commits are made, then we store an excessive number of files.

I think it's possible to set up a system as follows:
- When a PR is submitted, it will go through CI and produce some artifacts tied to that PR. These will come as a zip and that's unavoidable.
- When a PR is merged into master, the CI workflow will upload the generated PDF to some kind of external repository. Something like Google Drive, AWS, or even a github pages site associated with this repo. This way, anyone who wants to preview the project can simply download from this link rather than sort through the artifacts.

For now, while this situation is still on-going, I'm going to continue tracking the PDFs in the repo even though it's causing some really annoying merge conflicts.
