### ISSUE TITLE
Outdated contributing guide

### ISSUE THREAD

**Issue by milesdai** [milesdai/TAoE3Solutions#19]
Since the major document restructuring and the switch over to siunitx V2, CONTRIBUTING.md has been outdated.

**Comment by jensenr30** [comment]
I happened to read a bit in the siunitx documentation - they recommended using the \qty{}{} function instead of the older \SI{}{} function.  Not sure why exactly, but here is a snippet from the user manual
![SumatraPDF_ztsAMvinGQ](https://user-images.githubusercontent.com/3083835/153491395-e02215f6-8095-41a8-b355-53d00f400859.png)

**Comment by milesdai** [comment]
Yeah, I'm aware that this is the latest recommendation for siunitx v3. I decided to opt to the version 2 syntax for now since V3 is still quite new (< 1 year old) and the \SI and \si syntax is backwards compatible. Just wanted to keep this project as accessible to as possible for people trying to build it on their own.

**Comment by milesdai** [comment]
Resolved in 21f8d6e.
